### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by dok441** [DKFN/ogk_gg#7]
Sometimes I noticed this error, even though the round hadn't started yet.
![deat](https://user-images.githubusercontent.com/7480655/73305711-bc653e00-422b-11ea-8f74-00492bd3d657.png)

**Comment by DKFN** [comment]
Hi,

Thanks for reporting !

I think it might be a mistake on our changes to Onset's default weapon behavior.
We will be working on a fix soon :)

**Comment by DKFN** [comment]
Hi,

The issue should be fixed in the [develop](https://github.com/DKFN/ogk_gg/tree/develop) branch.

The develop branch also contain some of the features of 0.4 so I would advise you to wait for the release of 0.4 (around this weekend) before updating as they need more testing.
